=== hmcts/cpp-context-system-scheduling/systemscheduling-command/systemscheduling-command-api/src/raml/json/schema/systemscheduling.command.schedule-job.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": {
    "uuid": {
      "type": "string",
      "pattern": "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$"
    }
  },
  "type": "object",
  "properties": {
    "id": {
      "$ref": "#/definitions/uuid"
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "type": {
      "enum": [
        "REST"
      ]
    },
    "parameters": {
      "type": "object",
      "properties": {
        "endpointDefinition": {
          "type": "object",
          "properties": {
            "baseUri": {
              "type": "string"
            },
            "resource": {
              "type": "string"
            },
            "mediaType": {
              "type": "string"
            },
            "queryParams": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "additionalProperties": false,
          "required": [
            "baseUri",
            "resource",
            "mediaType"
          ]
        },
        "method": {
          "enum": [
            "POST"
          ]
        },
        "envelope": {
          "type": "object",
          "properties": {
            "_metadata": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                },
                "correlation": {
                  "type": "object",
                  "properties": {
                    "client": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "client"
                  ]
                },
                "context": {
                  "type": "object",
                  "properties": {
                    "session": {
                      "type": "string"
                    },
                    "user": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "user"
                  ]
                }
              },
              "required": [
                "id",
                "name"
              ]
            }
          },
          "required": [
            "_metadata"
          ]
        },
        "capability": {
          "type": "string",
          "description": "Name of capability to be checked prior to job execution. If capability is disabled then job execution will be abandon"
        }
      },
      "additionalProperties": false,
      "required": [
        "endpointDefinition",
        "method",
        "envelope"
      ]
    },
    "cronExpression": {
      "type": "string",
      "description": "Accepted Cron Expression Examples : please refer to http://www.quartz-scheduler.org/documentation/quartz-2.1.x/tutorials/crontrigger.html#format"
    }
  },
  "additionalProperties": false,
  "required": [
    "id",
    "name",
    "description",
    "type",
    "parameters",
    "cronExpression"
  ]
}

=== hmcts/cpp-context-system-scheduling/systemscheduling-integration-test/src/test/resources/systemscheduling.command.schedule-job.json
{
  "id": "JOB_ID",
  "name": "TestSchedulerJob",
  "description": "A test scheudler job that when triggered will call scheduler service to schedule a new job",
  "type": "REST",
  "parameters": {
    "endpointDefinition": {
      "baseUri": "http://localhost:8080/mi-service/command/api/rest/mi",
      "resource": "/generate-case-report",
      "mediaType": "mi.command.generate-case-report",
      "queryParams": [
        "xyz"
      ]
    },
    "method": "POST",
    "envelope": {
      "_metadata": {
        "id": "861c9430-7bc6-4bf0-b549-6534394b8d65",
        "name": "mi.command.generate-case-report",
        "correlation": {
          "client": "d51597dc-2526-4c71-bd08-5031c79f11e1"
        },
        "context": {
          "session": "45b0c3fe-afe6-4652-882f-7882d79eadd9",
          "user": "72251abb-5872-46e3-9045-950ac5bae399"
        }
      },
      "payload": {
        "caseId": "JOB_ID",
        "URN": "jhgjhg",
        "xyz": "jhgjhg",
        "abc": "jhgjhg",
        "adsfa": ""
      }
    }
  },
  "cronExpression": "0/2 * * * * ?"
}

=== hmcts/cpp-context-system-scheduling/systemscheduling-domain/systemscheduling-domain-event/src/test/resources/system.command.schedule-with-no-query-params.json
{
  "id": "36c9ac9b-a75e-412e-a48b-32050f38cf11",
  "name": "MIReport",
  "description": "Generates reports for the cases",
  "type": "REST",
  "parameters": {
    "endpointDefinition": {
      "baseUri": "http://localhost:8080/mi-command-api/command/api/rest/mi",
      "resource": "/generate-case-report",
      "mediaType": "mi.command.generate-case-report"
    },
    "method": "POST",
    "envelope": {
      "_metadata": {
        "id": "861c9430-7bc6-4bf0-b549-6534394b8d65",
        "name": "%s",
        "correlation": {
          "client": "d51597dc-2526-4c71-bd08-5031c79f11e1"
        },
        "context": {
          "session": "45b0c3fe-afe6-4652-882f-7882d79eadd9",
          "user": "7aee5dea-b0de-4604-b49b-86c7788cfc4b"
        }
      }
    }
  },
  "cronExpression": "0 0/2 * * * ?"
}

=== hmcts/cpp-context-system-scheduling/systemscheduling-command/systemscheduling-command-api/src/raml/json/systemscheduling.command.schedule-job.json
{
  "id": "36c9ac9b-a75e-412e-a48b-32050f38cf11",
  "name": "MIReport",
  "description": "Generates reports for the cases",
  "type": "REST",
  "parameters": {
    "endpointDefinition": {
      "baseUri": "http://localhost:8080/mi-command-api/command/api/rest/mi",
      "resource": "/case-started/{caseId}/{URN}",
      "mediaType": "mi.command.generate-case-report",
      "queryParams": [
        "xyz"
      ]
    },
    "method": "POST",
    "envelope": {
      "_metadata": {
        "id": "861c9430-7bc6-4bf0-b549-6534394b8d65",
        "name": "mi.command.generate-case-report",
        "correlation": {
          "client": "d51597dc-2526-4c71-bd08-5031c79f11e1"
        },
        "context": {
          "session": "45b0c3fe-afe6-4652-882f-7882d79eadd9",
          "user": "72251abb-5872-46e3-9045-950ac5bae399"
        }
      },
      "caseId": "786876876",
      "URN": "jhgjhg",
      "xyz": "jhgjhg",
      "abc": "jhgjhg",
      "adsfa": ""
    }
  },
  "cronExpression": "0 0/0 * * * ?"
}
